### ISSUE TITLE
Suggest porting interpreter to transpiler

### ISSUE THREAD

**Issue by nguyenphuminh** [pashmaklang/pashmak#163]
**Fillable**
you are suggesting **New feature** or **Changing feature**? - change
- [x] did you read the Pashmak documentation?
- [x] are you sure this feature already not exists?

**Suggest porting interpreter to transpiler**
The language is currently very slow, as it's interpreted inside an interpreted language like Python (and Python is already too slow). I think this is a really easy problem to fix, I'm surprised that you haven't thought of this before. You can just change Pashmak from an interpreted language to a Python-transpiled language. It solves a lot of problem:
- The speed is greatly improved, since the old Pashmak is interpreted inside an interpreted language (that's Python), now it's just Python.
- Making it transpiled to Python also makes it compatible with Python, so that fixes the `Pashmak is really depended to the Python interpreter. Eval syntax, datatypes, and lot of other features are handled by Python.` problem that you've mentioned in https://github.com/pashmaklang/pashmak/issues/159.
- Transpiler is not too hard to create (imo), and Pashmak is syntactically similar to Python so it's probably even easier to create than just maintaining the current interpreter, and it brings way more pros than cons.

Love Pashmak by the way!

**Comment by parsampsh** [comment]
In fact, the main problem is that when I started this project, I never thought it would be completed and it was just a project for fun. That's why I didn't think about these problems at that time. And you are absolutely right. The problem is that applying these changes to the whole project is very heavy and time consuming. It would not be a problem if this was done from the beginning. But applying this to the whole project is currently very heavy and time consuming.
