### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by mehanalavimajd** [pashmaklang/pashmak#50]
I know that Pashmak has standard modules like sys , random and os but I think we have to make a module manager so developers can download the pashmak modules that are not standard. We can name pmm because it means Pashmak Module Manager

**Comment by Paptoos** [comment]
Like `pip` ???

**Comment by parsampsh** [comment]
Yes. I Wanna start something like this. Also if @Paptoos @mehanalavimajd Both of you can contribute i can give commit access to you for that. then we can work on that. Also for name, I like `parham`(Par hayam, pashm hayam (: ). what is your say?

**Comment by Paptoos** [comment]
I think about pashmak package manager ( ppm )
I can contribute !

**Comment by parsampsh** [comment]
I Think ppm is not unique word symbol.
https://www.google.com/search?channel=fs&client=ubuntu&q=ppm

**Comment by parsampsh** [comment]
> I think about pashmak package manager ( ppm )
> I can contribute !

Thanks. also we should write it with pashmak :)

**Comment by Paptoos** [comment]
Write it in pashmak is impossible now ! But if problems are solved and new features are added to Pashmak while writing, it can be written with Pashmak

**Comment by parsampsh** [comment]
> Write it in pashmak is impossible now ! But if problems are solved and new features are added to Pashmak while writing, it can be written with Pashmak

We can fix Pashmak bugs and add the required features at the same time as we write package manager it. for now, we should wait and make ready `0.6`. then we can think about it.

**Comment by mehanalavimajd** [comment]
> Like `pip` ???

Exactly like that

**Comment by mehanalavimajd** [comment]
> > Write it in pashmak is impossible now ! But if problems are solved and new features are added to Pashmak while writing, it can be written with Pashmak
> 
> We can fix Pashmak bugs and add the required features at the same time as we write package manager it. for now, we should wait and make ready `0.6`. then we can think about it.

Yes It's good idea

**Comment by hasan-kashi** [comment]
> 
> 
> I Think ppm is not unique word symbol.
> https://www.google.com/search?channel=fs&client=ubuntu&q=ppm

ppm is a package manager for Perl.

**Comment by parsampsh** [comment]
I suggest **Parham**.

**Comment by mehanalavimajd** [comment]
I suggest pmm 
Pashmak Module Manager

**Comment by sami2020pro** [comment]
> I suggest pmm
> Pashmak Module Manager

I love this abbreviation.

**Comment by parsampsh** [comment]
Hello there. I wrote a system design for the package manager.
(i written a package manager and know about structure of them).

Please read the following notes and then let me know do you want to contribute to create this project from zero together.

# System design for Parham Package Manager
We need the following sectiions for our program.

This program should be written modular.

The needed sections are listed below:

## 1. Commandline
1. We need a command line parsing and handling part. this gets the command line arguments and parses them.
also with this, we can handle the commands (This is ready).

## 2. Parhamfile
We need a section to read `Parhamfile` and parse it. the `Parhamfile` is a file to configure and define a package.
This is something like `composer.json` in composer(php), `setup.py` in pip(python), etc.
We need a part in our program to read this file and parse that syntax and load and parse options.
A Example for Parhamfile:

```
name my-package
description description of my package

require gh:vendor1/package1 > 1.0
require gh:vendor2/package2 >= 3.0

require pashmak >= 0.7 # the pashmak version
require parham >= 0.1 # the parham version

conflict gh:foo/bar <= 5.0
# ...
```

Also we will syntax highlighter of this format to vscode-pashmak

## 3. Versioning
We need a library for parsing and comparing the versions.
This allows us to compare that for example `1.0 > 0.9`.

## 4. Package model
We need the package model. Package model should handle everything about packages.
Means we give name and source of a package to that and that gives some informations to us.
This system should load packages from github and local directories.
Means in the back of this system, we should handle drivers.
for example, `gh:sami2020pro/polor-pashm` points to https://github.com/sami2020pro/polor-pashm.
and `f:/home/parsa/somelib/` points to a local directory.
Package versions should be handled by Git. means, our package manager should use git tags as package versions.
If we are using a package on github, our program should load list of versions from github git tags.
The example code for the package model class:

```
$pkg1 = Package('gh:sami2020pro/polor-pashm')
$versions = $pkg1->get_versions()
$pkg2 = Package('f:/home/parsa/somelib')
$versions = $pkg2->get_versions()
println $pkg2->name, $pkg2->description, # ...
```

## 5. Dependency and conflict solver
we need a dependency and conflict solver. the Solver, is a system to get some commands (install and remove),
and solve dependencies and conflicts in that. for example, i wanna install `foo` package. this package has some
dependencies and conflicts. the Solver, should list and solve all if depends and conflicts of packages.
This is a very complicated section in program.
Also this system should handle errors. for example we wanna install x and y
x requires `z >= 3.0`.
and y requires `z <= 2.0`
so, the x and y packages cannot be installed alongside together.
because x requires z>=3.0 and y requires z<=2.0!!

## 6. Package directory
this system is for handling packages directory.
For example, i have project, now i wanna install some packages for my project.
the packages should be stored at `/path/to/my-project/pashmak_modules/`.
means the packages should be installed in `pashmak_modules` directory at the root of the project.
(line `node_modules/` and `vendor/`).
This part of program should handle this system.
Now, we can load modules from this directory in our program.
This is possible by only adding path of `pashmak_modules/` to the path.

```
import @sys
sys.path.add($__dir__ + '/pashmak_modules')

import @some_installed_package
# means /path/to/pashmak_modules/some_installed_package.pashm
# OR /path/to/pashmak_modules/some_installed_package/__init__.pashm
```

## 7. The installer and remover
this part will be used in this flow:
- user tells i want to install x and y
- then, we pass x and y to Solver
- finally, solver tells us which packages should be install/remove/upgrade/downgrade
- then, pass that packages one by one to installer and remover
means, this part finally installs/removes a package in package directory(pashmak_modules/)

## 8. Commands
generally, We need the following commands:
- list: shows list of installed packages
- show: show a package
- install: install a package
- remove: remove a package

Also we need a option named `--global|-g`. this option sets program in global state.
this means directory packages will be considered `<home>/.parham/pashmak_modules/` instead of
`<current-directory>/pashmak_modules`.
This allows us to install some packages globally.

## 9. More features
We can also add more features after creating the base structure of our package manager.
Like `create-project` command for creating a project from a template and more...

---

If you want and accept, we can create this project as a great team work.

**Comment by parsampsh** [comment]
Also each one of you accept and wants to contribute, i suggest you **Surely read Pashmak documentation again** to learn it better(pashmak its ready and have potential for writing package manager with it).

**Comment by parsampsh** [comment]
Each one wants to be int the project please let me know soon.

**Comment by amirghazi87** [comment]
Hello @parsampsh
I want to contribute to this project and I read the doc to learn better than I start

**Comment by parsampsh** [comment]
I created repository https://github.com/pashmaklang/parham

**Comment by parsampsh** [comment]
> Hello @parsampsh
> I want to contribute to this project and I read the doc to learn better than I start

I'll invite you to the repository

**Comment by mehanalavimajd** [comment]
I want to contribute too.

**Comment by parsampsh** [comment]
> I want to contribute too.

Great. i invited you

**Comment by parsampsh** [comment]
Some part of Parham is done. I'll start continuing development on Parham soon.
I'll close this issue.
