### ISSUE TITLE
stable syntax and language support

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#83]
I created a language support project for **Visual Studio Code** with **yo** and use **TypeScript** language.
 I need s stable syntax, Please work on the stable syntax procedure. If it still works and receives an update, I will update it for the extension and it is not a problem, Just a **notice**.

**Comment by parsampsh** [comment]
Actually, This needs a syntax grammer. but currently i don't know how to make a standard grammer for pashmak syntax.
But for now, i wrote a short description for strucuture of pashmak's syntax.

# Structure of pashmak syntax

## Variables
Variables should be started with `$`. then, the name of variable. name only can contains Alpha-Bet characters(in all of languages), `_`, `.` and `&` characters. `$<name>`. Literal chars cannot be in name of variable (like `/+-*%...`)

## Eval syntax
The **Eval**, means calculation code. for example, `2 + 2` is a eval. also `$x - 10 * (30 + $other_var)` is a eval. or `"hello " + ("wor" + "ld " + str($x))`. This syntax is even like python eval syntax(This means support for strings and dictonaries with `{}`, etc). only need consider variables with `$`.

## Blocks & statements
usually, blocks and statements in pashmak is like this: starts with `<x>` and ends with `end<x>`. for example, `if endif`, `while endwhile`, `func endfunc`...

### If..elif..else..endif
If statement starts with `if <condition>`.
Then, elif block can be started with `elif <condition>`.
then, the else block can be started with `else`.
and the if block will be closed with `endif`.

### while loop
The while loop starts with `while <condition>` and ends with `endwhile`.
Also there is two other keywords: `break` and `continue`.

### func block
function block can be started with `func <name>?($<var>)`.
The `(...)` is optional. also, this can be empty, for example `func somefunc()`.
But this cannot be empty and have a variable inside it, for example `func somefunc($somevar)`.
The function name should not contains literals(like variables), but can have `.`, `_` and alpha-bet.
Then, function block can be closed with `endfunc` keyword.

### class block
Class block can be started with `class <Name> ? < <parent>`.
For example, `class Someclass`. The class name should not contains literals(like variables), but can have `.`, `_` and alpha-bet.
Also there is a option part, the `< ParentClassName`. this is extend symbol. `class Child < Father`.
then, class block can be closed with `endclass` keyword.

### namespace block
The namespace block can be started with `namespace <nsname>`.
for example `namespace App`. the namespace name cannot have literals and `.`. only alpha-bet and `_`.
then, namespace block can be closed with `endnamespace` keyword.
Also there is two aliases: `ns` for `namespace` and `endns` for `endnamespace`.

### Complicated
All of this statement can be used compilcated.

### `<condition>`
In some parts of above statments, we used `<condition>`. Value of this, is even like python eval syntax structure(consider variables with `$`).
for example, `while $x == 2`, or `if 100 > ($n * 10)`.

### `import` and `import_once` keywords(commands)
Syntax of this commands is like this: `import <eval>`, `import_once <eval>`. instead of `<eval>`, can be a string with Eval syntax structure.
For example: `import $__dir__ + '/some/path.pashm'`.

### Total keywords
Total keywords about above statements: `if`, `elif`, `else`, `endif`, `while`, `endwhile`, `break`, `continue`, `func`, `endfunc`, `class`, `endclass`, `namespace`, `endnamespace`, `ns`, `endns`, `import`, `import_once`.

## Calling functions
Syntax of calling functions: `func_name(<args...>)`.
Arguments can be empty: `func_name()`. also can be filled: `func_name($somevar + 10 - 1 + other_func_output())`.
The structure of string of between `()` is even like python eval syntax(consider variables with `$`).

---

Is this helpful for you? Do you need other information?

**Comment by sami2020pro** [comment]
Thanks!!!
